#!/usr/bin/env python3
"""MQTT Cloud Publisher — upload pipeline JSON reports to WISE-IoT DataHub.

Reads the JSON report generated by the inference pipeline (generate_report()
in src/utils.py) and publishes frame-by-frame data to the WISE-IoT RabbitMQ
MQTT broker. DataHub ingests the messages and the Dashboard queries them via
the DataHub-SimpleJson datasource plugin.

Architecture:
    PC (this script) ──MQTT──▶ WISE-EnSaaS/RabbitMQ ──▶ DataHub ──SimpleJson──▶ Dashboard

Usage:
    # Upload a single JSON report (batch mode)
    uv run python scripts/mqtt_cloud_publisher.py --report code/data/report.json

    # Stream pipeline output in realtime (pipe mode)
    uv run python src/main.py --input demo/input/test.mp4 --json-stdout |
        uv run python scripts/mqtt_cloud_publisher.py --pipe

    # Preview without connecting (dry-run)
    uv run python scripts/mqtt_cloud_publisher.py --report code/data/report.json --dry-run

Reference:
    - vendor/wise-iot-docs/IoTsuite MQTT子设备.docx
    - https://github.com/WISE-PaaS/example-py-iothub-sso
"""

import argparse
import datetime
import json
import logging
import sys
import time
from pathlib import Path
from typing import Any

import paho.mqtt.client as mqtt
import yaml

# ---------------------------------------------------------------------------
# config loading
# ---------------------------------------------------------------------------

ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = ROOT / "configs" / "mqtt_cloud.yaml"

logger = logging.getLogger("mqtt_publisher")


def load_config(path: Path = CONFIG_PATH) -> dict[str, Any]:
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


# ---------------------------------------------------------------------------
# IoTSuite payload builder
# ---------------------------------------------------------------------------


def build_payload(
    device_id: str,
    module_name: str,
    properties: dict[str, Any],
    prop_config: dict[str, dict[str, str]],
) -> dict[str, Any]:
    """Build a single-frame MQTT payload conforming to the IoTSuite spec.

    Output format:
        {
          "d_id": "<device_id>",
          "services": {
            "<module_name>": {
              "properties": {
                "risk_score":   { "value": 8.9,  "dataType": "float" },
                "risk_level":   { "value": "low", "dataType": "string" },
                ...
              }
            }
          },
          "ts": "2026-07-14T18:04:00+08:00"
        }
    """
    props_payload: dict[str, dict[str, Any]] = {}
    for key, value in properties.items():
        if key not in prop_config:
            continue
        cfg = prop_config[key]
        props_payload[cfg["name"]] = {
            "value": value,
            "dataType": cfg["datatype"],
        }

    return {
        "d_id": device_id,
        "services": {
            module_name: {"properties": props_payload},
        },
        "ts": datetime.datetime.now().astimezone().isoformat(timespec="seconds"),
    }


# ---------------------------------------------------------------------------
# MQTT publisher
# ---------------------------------------------------------------------------


class MQTTCloudPublisher:
    """Publishes pipeline frame data to WISE-IoT via MQTT."""

    def __init__(self, config: dict[str, Any]) -> None:
        cfg = config["mqtt"]
        self._device_id: str = cfg["device_id"]
        self._topic = cfg["topic_report"].format(device_id=self._device_id)
        self._qos: int = cfg["qos"]
        self._interval: float = cfg["publish_interval_sec"]

        mapping = config["module_mapping"]
        self._module_name: str = mapping["module_name"]
        self._prop_config: dict[str, dict[str, str]] = mapping["properties"]

        self._client = mqtt.Client(
            client_id=cfg["client_id"],
            protocol=mqtt.MQTTv311,
        )
        self._client.username_pw_set(cfg["username"], cfg["password"])
        self._client.on_connect = self._on_connect
        self._client.on_publish = self._on_publish

        self._published_count = 0
        self._connected = False

    # --- callbacks ---

    @staticmethod
    def _on_connect(client, userdata, flags, rc):
        if rc == 0:
            logger.info("MQTT connected (rc=%d)", rc)
            userdata["connected"] = True
        else:
            logger.error("MQTT connection failed (rc=%d)", rc)

    @staticmethod
    def _on_publish(client, userdata, mid):
        userdata["count"] = userdata.get("count", 0) + 1

    # --- public API ---

    def connect(self) -> None:
        cfg = load_config()["mqtt"]
        logger.info(
            "Connecting to %s:%d as %s ...",
            cfg["broker_host"], cfg["broker_port"], cfg["client_id"],
        )
        userdata = {"connected": False, "count": 0}
        self._client.user_data_set(userdata)
        self._client.connect(cfg["broker_host"], cfg["broker_port"], cfg["keepalive_sec"])
        self._client.loop_start()

        # Wait for connection
        for _ in range(50):  # 5 second timeout
            if userdata["connected"]:
                self._connected = True
                logger.info("MQTT connected successfully")
                return
            time.sleep(0.1)

        raise ConnectionError("MQTT connection timed out after 5 seconds")

    def publish_frame(self, frame_data: dict[str, Any]) -> None:
        """Publish a single frame's worth of properties."""
        payload = build_payload(
            self._device_id,
            self._module_name,
            frame_data,
            self._prop_config,
        )
        payload_json = json.dumps(payload, ensure_ascii=False)

        info = self._client.publish(self._topic, payload_json, qos=self._qos)
        if info.rc != mqtt.MQTT_ERR_SUCCESS:
            logger.warning("Publish queue full (rc=%d), backing off", info.rc)
            time.sleep(0.5)

        time.sleep(self._interval)

    def publish_report(self, report: dict[str, Any]) -> int:
        """Publish all frames from a pipeline JSON report.

        Returns the number of frames published.
        """
        frames = report.get("frame_details", [])
        if not frames:
            logger.warning("Report contains no frame_details; nothing to publish")
            return 0

        logger.info("Publishing %d frames to %s ...", len(frames), self._topic)
        self._published_count = 0

        for i, frame in enumerate(frames):
            # Extract per-frame properties from the pipeline's frame_details
            properties = {
                "frame_idx": frame.get("frame_idx", i),
                "risk_score": round(frame.get("score", 0.0), 2),
                "risk_level": frame.get("level", "low"),
                "detections_count": frame.get("detections_count", 0),
                "high_risk_count": frame.get("high_risk_count", 0),
                "fps": frame.get("fps", 0.0),
            }
            self.publish_frame(properties)
            self._published_count += 1

            if (i + 1) % 100 == 0:
                logger.info("  %d/%d frames published", i + 1, len(frames))

        logger.info(
            "Finished: %d frames published to %s", self._published_count, self._topic
        )
        return self._published_count

    def close(self) -> None:
        self._client.loop_stop()
        self._client.disconnect()
        logger.info("MQTT disconnected. Total published: %d", self._published_count)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main():
    ap = argparse.ArgumentParser(
        description="Publish pipeline JSON reports to WISE-IoT via MQTT"
    )
    ap.add_argument(
        "--report", type=Path,
        help="Path to a pipeline JSON report (from generate_report())",
    )
    ap.add_argument(
        "--config", type=Path, default=CONFIG_PATH,
        help="Path to mqtt_cloud.yaml (default: configs/mqtt_cloud.yaml)",
    )
    ap.add_argument(
        "--dry-run", action="store_true",
        help="Show what would be published without connecting to MQTT",
    )
    ap.add_argument(
        "--pipe", action="store_true",
        help="Read JSON frames from stdin (one per line) instead of a file",
    )
    ap.add_argument(
        "--verbose", "-v", action="store_true",
        help="Enable debug logging",
    )

    args = ap.parse_args()
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )

    # --- validate config placeholder ---
    cfg = load_config(args.config)
    mqtt_cfg = cfg["mqtt"]
    if "YOUR" in mqtt_cfg["device_id"] or "YOUR" in mqtt_cfg["username"]:
        logger.error(
            "MQTT credentials not configured.\n"
            "  1. Register device in IoTSuite Portal\n"
            "  2. Fill configs/mqtt_cloud.yaml with: broker_host, device_id, username, password\n"
            "  3. Re-run this script"
        )
        sys.exit(1)

    # --- load data ---
    if args.pipe:
        frames: list[dict[str, Any]] = []
        for line in sys.stdin:
            line = line.strip()
            if line:
                frames.append(json.loads(line))
        report: dict[str, Any] = {"frame_details": frames}
    elif args.report:
        with open(args.report, encoding="utf-8") as f:
            report = json.load(f)
    else:
        logger.error("Either --report <path> or --pipe must be provided")
        sys.exit(1)

    # --- dry-run mode ---
    if args.dry_run:
        summary = report.get("summary", {})
        frames = report.get("frame_details", [])
        print(f"=== DRY RUN ===")
        print(f"  Report summary: {json.dumps(summary, indent=2)}")
        print(f"  Frames to publish: {len(frames)}")
        print(f"  Topic: {mqtt_cfg['topic_report'].format(device_id=mqtt_cfg['device_id'])}")
        if frames:
            print(f"  Sample payload for frame 0:")
            publisher = MQTTCloudPublisher(cfg)
            sample = build_payload(
                mqtt_cfg["device_id"],
                cfg["module_mapping"]["module_name"],
                {
                    "frame_idx": frames[0].get("frame_idx", 0),
                    "risk_score": frames[0].get("score", 0.0),
                    "risk_level": frames[0].get("level", "low"),
                    "detections_count": frames[0].get("detections_count", 0),
                    "high_risk_count": frames[0].get("high_risk_count", 0),
                    "fps": frames[0].get("fps", 0.0),
                },
                cfg["module_mapping"]["properties"],
            )
            print(f"  {json.dumps(sample, indent=2, ensure_ascii=False)}")
        print(f"=== End DRY RUN ===")
        return

    # --- publish ---
    publisher = MQTTCloudPublisher(cfg)
    try:
        publisher.connect()
        publisher.publish_report(report)
    except Exception as e:
        logger.error("Publishing failed: %s", e)
        raise
    finally:
        publisher.close()


if __name__ == "__main__":
    main()
